spring.application.name=USER-SERVICE
server.port=8082

jwt.secretKey=this_is_my_secret_key_for_jwt_token_generation
jwt.refreshTokenExpiry=604800000

spring.datasource.url=jdbc:mysql://localhost:3306/auth_service_db_dev?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update

management.endpoints.web.exposure.include[0]=health
management.endpoints.web.exposure.include[1]=info

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.try-it-out-enabled=false

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# Gemini AI
app.gemini.api-key=AIzaSyBdL9A5ovmjRTeuvu4cfd28gp5wsjJgJZE
